service: track

# [START runtime]
runtime: python27
api_version: 1
threadsafe: true
# [END runtime]

# [START handlers]
handlers:
  - url: "/service-worker.js"
    secure: always
    static_files: service-worker.js
    upload: service-worker.js
    mime_type: application/javascript

  - url: /(precache-manifest.*)$
    secure: always
    mime_type: application/javascript
    static_files: \1
    upload: (precache-manifest.*)$

  - url: /(.*\.js)$
    secure: always
    static_files: \1
    upload: .*\.js$
    mime_type: application/javascript

  - url: /(.*\.(css|map|png|jpg|svg|ico|json|txt|woff))$
    secure: always
    static_files: \1
    upload: .*\.(css|map|png|jpg|svg|ico|json|txt|woff)$

  - url: "/"
    secure: always
    static_files: index.html
    upload: index.html

  - url: "/(.*)"
    secure: always
    static_files: index.html
    upload: index.html
# [END handlers]
